export const CHANGE_BASE_CURRENCY = 'CHANGE_BASE_CURRENCY';
export const CHANGE_SHIFT_CURRENCY = 'CHANGE_SHIFT_CURRENCY';
export const GET_CURRENCY = 'GET_CURRENCY';
export const INCREASE_CURRENCY = 'INCREASE_CURRENCY';
export const DECREASE_CURRENCY = 'DECREASE_CURRENCY';

